[build]
  command = "ng build --configuration production"
  publish = "dist/tournament_website/browser/browser"

[plugins]
  package = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200